version: 2

models:
  # Dimension Models
  - name: dim_listings_cleansed
    description: >
      Cleansed dimension table for Airbnb listings. This table contains verified,
      cleaned data about individual property listings, ensuring data quality and
      consistency for downstream analysis.
    columns:
      - name: listing_id
        description: Primary key for the listing. Unique identifier for each property listing.
        tests:
          - unique
          - not_null

      - name: host_id
        description: Foreign key to the host dimension table. Identifies the host who owns or manages the listing.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: >
          Categorizes the type of space offered. This is a standardized field with
          four possible values representing different accommodation types.
        tests:
          - accepted_values:
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]

      - name: minimum_nights
        description: The minimum number of nights a guest can book the listing for.
        tests:
          # - dbt_utils.positive_value
          - positive_value

  - name: dim_hosts_cleansed
    description: >
      Cleansed dimension table for Airbnb hosts. Contains verified information about
      property hosts, including their superhost status and identity details.
    columns:
      - name: host_id
        description: Primary key for the host. Unique identifier for each Airbnb host.
        tests:
          - not_null
          - unique

      - name: host_name
        description: The display name of the host on the Airbnb platform.
        tests:
          - not_null

      - name: is_superhost
        description: >
          Boolean flag indicating the host's superhost status. 't' for superhosts,
          'f' for regular hosts.
        tests:
          - accepted_values:
              values: ["t", "f"]

  - name: dim_listings_w_hosts
    description: >
      Enhanced dimension table that combines listing and host information. This table
      provides a denormalized view of listings with their corresponding host details.
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb_source', 'listings')

    columns:
      - name: price
        description: >
          The nightly price for the listing in the local currency. Expected to be
          a numeric value within reasonable bounds for Airbnb pricing.
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 0
              max_value: 10000
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 0
              max_value: 10000

      - name: host_is_superhost
        description: Indicates whether the host of this listing has achieved superhost status.
        test:
          - not null
